"""
Tests for the real (non-"mock") OCR/Vision/STT providers added for the
Voice/Video phase:
  - app/multimodal/ocr.py's TesseractOCRProvider - runs the actual
    local `tesseract` binary (installed in this environment), no
    mocking needed for its happy path.
  - app/multimodal/vision.py's ClaudeVisionProvider - the Anthropic
    client is mocked throughout (same pattern as
    tests/test_claude_narrative.py), no real API key/call needed.
  - app/multimodal/speech_to_text.py's WhisperSTTProvider - the
    faster-whisper model itself is monkeypatched (loading the real
    model downloads it from Hugging Face, which this sandbox's network
    policy blocks - the same reason tests/test_embeddings.py doesn't
    load a real model in CI either); the ffmpeg/PyAV decoding path
    that makes video transcription "just work" is exercised for real
    with a synthetic video generated by the `ffmpeg` binary.

Defaults (OCR_PROVIDER/STT_PROVIDER/VISION_PROVIDER=mock) are
unchanged - see tests/test_multimodal_processors.py for the
still-passing mock-path coverage.
"""

import io
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path
from types import SimpleNamespace

import pytest
from PIL import Image, ImageDraw

from app.multimodal.ocr import TesseractOCRProvider, get_ocr_provider
from app.multimodal.speech_to_text import WhisperSTTProvider, get_stt_provider
from app.multimodal.video_processor import _sample_frame_pngs, process_video
from app.multimodal.vision import ClaudeVisionProvider, get_vision_provider


@pytest.fixture(autouse=True)
def _isolated_metadata_repository(tmp_path, monkeypatch):
    """ClaudeVisionProvider.describe() logs usage via track_llm_call() - same isolation as tests/test_claude_narrative.py."""

    from app.api import storage_api
    from app.metadata.sqlite_repository import SQLiteMetadataRepository

    monkeypatch.setattr(
        storage_api, "metadata_repository", SQLiteMetadataRepository(tmp_path / "metadata.db")
    )


def _text_image_bytes(text: str) -> bytes:
    image = Image.new("RGB", (400, 80), color="white")
    draw = ImageDraw.Draw(image)
    draw.text((10, 20), text, fill="black")
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


# ---------------------------------------------------------------------
# TesseractOCRProvider - real, no mocking
# ---------------------------------------------------------------------


def test_tesseract_extracts_real_text_from_an_image():
    provider = TesseractOCRProvider()
    text, is_mock = provider.extract_text(_text_image_bytes("Hello Legal World"), "scan.png")

    assert "Hello Legal World" in text
    assert is_mock is False


def test_tesseract_raises_on_unreadable_bytes():
    provider = TesseractOCRProvider()

    with pytest.raises(RuntimeError, match="Tesseract OCR failed"):
        provider.extract_text(b"not an image at all", "corrupt.png")


def test_get_ocr_provider_returns_tesseract_when_configured(monkeypatch):
    monkeypatch.setattr("app.multimodal.ocr.get_settings", lambda: SimpleNamespace(ocr_provider="tesseract"))

    assert isinstance(get_ocr_provider(), TesseractOCRProvider)


def test_get_ocr_provider_rejects_unknown_provider(monkeypatch):
    monkeypatch.setattr("app.multimodal.ocr.get_settings", lambda: SimpleNamespace(ocr_provider="nonsense"))

    with pytest.raises(RuntimeError, match="Unknown OCR_PROVIDER"):
        get_ocr_provider()


# ---------------------------------------------------------------------
# ClaudeVisionProvider - Anthropic client mocked
# ---------------------------------------------------------------------


@dataclass
class _FakeSettings:
    anthropic_api_key: str = "test-key"
    analysis_model: str = "claude-opus-5"
    vision_provider: str = "claude"


def _fake_anthropic_client(response_text: str):
    block = SimpleNamespace(type="text", text=response_text)
    usage = SimpleNamespace(input_tokens=15, output_tokens=25)
    response = SimpleNamespace(content=[block], usage=usage)

    class _FakeMessages:
        def create(self, **kwargs):
            _FakeMessages.last_call = kwargs
            return response

    return SimpleNamespace(messages=_FakeMessages())


def test_claude_vision_describes_an_image(monkeypatch):
    monkeypatch.setattr("app.multimodal.vision.get_settings", lambda: _FakeSettings())
    monkeypatch.setattr("anthropic.Anthropic", lambda api_key: _fake_anthropic_client("A photo of a damaged vehicle."))

    provider = ClaudeVisionProvider()
    caption, is_mock = provider.describe(_text_image_bytes("irrelevant"), "scene.png")

    assert caption == "A photo of a damaged vehicle."
    assert is_mock is False


def test_claude_vision_sends_the_image_as_a_base64_content_block(monkeypatch):
    monkeypatch.setattr("app.multimodal.vision.get_settings", lambda: _FakeSettings())
    fake_client = _fake_anthropic_client("caption")
    monkeypatch.setattr("anthropic.Anthropic", lambda api_key: fake_client)

    provider = ClaudeVisionProvider()
    provider.describe(_text_image_bytes("irrelevant"), "scene.png")

    sent_content = fake_client.messages.last_call["messages"][0]["content"]
    image_block = next(b for b in sent_content if b["type"] == "image")
    assert image_block["source"]["media_type"] == "image/png"
    assert isinstance(image_block["source"]["data"], str)


def test_claude_vision_rejects_unsupported_image_format(monkeypatch):
    monkeypatch.setattr("app.multimodal.vision.get_settings", lambda: _FakeSettings())
    monkeypatch.setattr("anthropic.Anthropic", lambda api_key: _fake_anthropic_client("caption"))

    provider = ClaudeVisionProvider()

    with pytest.raises(RuntimeError, match="unsupported image format"):
        provider.describe(b"fake tiff bytes", "scan.tiff")


def test_claude_vision_constructor_requires_api_key(monkeypatch):
    monkeypatch.setattr("app.multimodal.vision.get_settings", lambda: _FakeSettings(anthropic_api_key=""))

    with pytest.raises(RuntimeError, match="ANTHROPIC_API_KEY"):
        ClaudeVisionProvider()


def test_get_vision_provider_returns_claude_when_configured(monkeypatch):
    monkeypatch.setattr("app.multimodal.vision.get_settings", lambda: _FakeSettings())
    monkeypatch.setattr("anthropic.Anthropic", lambda api_key: _fake_anthropic_client("caption"))

    assert isinstance(get_vision_provider(), ClaudeVisionProvider)


# ---------------------------------------------------------------------
# WhisperSTTProvider - the model itself is monkeypatched; ffmpeg/PyAV
# decoding (what makes video "just work") is exercised for real.
# ---------------------------------------------------------------------


class _FakeWhisperModel:
    def __init__(self, transcript_text: str):
        self._transcript_text = transcript_text
        self.last_path: str | None = None

    def transcribe(self, path: str):
        self.last_path = path
        segment = SimpleNamespace(text=self._transcript_text)
        return [segment], SimpleNamespace(language="en")


def test_whisper_transcribes_audio_bytes_via_a_temp_file(monkeypatch):
    fake_model = _FakeWhisperModel(" Hello from the client. ")
    provider = WhisperSTTProvider()
    monkeypatch.setattr(provider, "_load_model", lambda: fake_model)

    transcript, is_mock = provider.transcribe(b"fake audio bytes", "call.mp3")

    assert transcript == "Hello from the client."
    assert is_mock is False
    assert fake_model.last_path.endswith(".mp3")
    assert not Path(fake_model.last_path).exists()  # cleaned up after transcription


def test_whisper_joins_multiple_segments():
    class _MultiSegmentModel:
        def transcribe(self, path):
            return (
                [SimpleNamespace(text="First sentence."), SimpleNamespace(text="Second sentence.")],
                SimpleNamespace(language="en"),
            )

    provider = WhisperSTTProvider()
    provider._load_model = lambda: _MultiSegmentModel()

    transcript, _ = provider.transcribe(b"fake audio bytes", "note.wav")

    assert transcript == "First sentence. Second sentence."


def test_whisper_wraps_transcription_failures():
    class _BrokenModel:
        def transcribe(self, path):
            raise ValueError("boom")

    provider = WhisperSTTProvider()
    provider._load_model = lambda: _BrokenModel()

    with pytest.raises(RuntimeError, match="Whisper transcription failed"):
        provider.transcribe(b"fake audio bytes", "call.mp3")


@pytest.mark.skipif(shutil.which("ffmpeg") is None, reason="ffmpeg not installed in this environment")
def test_whisper_transcribes_a_video_file_with_no_separate_demuxing_step(tmp_path, monkeypatch):
    """
    The whole point of WhisperSTTProvider handling video: no video-
    specific code path exists anywhere (app/multimodal/video_processor.py
    calls the exact same transcribe() audio_processor.py does) -
    faster-whisper's own PyAV-based decoding demuxes the audio stream
    out of the video container. This proves that decoding step works
    against a REAL video file (synthesized here, no network/fixture
    file needed), by handing it a video path and confirming the (fake)
    model was invoked with that same, still-decodable file.
    """

    video_path = tmp_path / "clip.mp4"
    subprocess.run(
        [
            "ffmpeg", "-y", "-f", "lavfi", "-i", "sine=frequency=440:duration=1",
            "-f", "lavfi", "-i", "testsrc=duration=1:size=160x120:rate=5",
            "-c:v", "libx264", "-c:a", "aac", "-shortest", str(video_path),
        ],
        check=True, capture_output=True,
    )
    video_bytes = video_path.read_bytes()

    fake_model = _FakeWhisperModel("Deposition audio transcribed from the video's audio track.")
    provider = WhisperSTTProvider()
    monkeypatch.setattr(provider, "_load_model", lambda: fake_model)

    transcript, is_mock = provider.transcribe(video_bytes, "clip.mp4")

    assert transcript == "Deposition audio transcribed from the video's audio track."
    assert is_mock is False
    assert fake_model.last_path.endswith(".mp4")

    # Confirm PyAV (what faster-whisper actually uses to decode) can
    # open this exact video and find a real, decodable audio stream -
    # the real mechanism this test's fake model call stands in for.
    import av

    with av.open(str(video_path)) as container:
        audio_streams = [s for s in container.streams if s.type == "audio"]
        assert len(audio_streams) == 1
        assert sum(1 for _ in container.decode(audio_streams[0])) > 0


def test_get_stt_provider_returns_whisper_when_configured(monkeypatch):
    monkeypatch.setattr("app.multimodal.speech_to_text.get_settings", lambda: SimpleNamespace(
        stt_provider="whisper", whisper_model_size="base", whisper_device="cpu", whisper_compute_type="int8",
    ))

    assert isinstance(get_stt_provider(), WhisperSTTProvider)


# ---------------------------------------------------------------------
# Video frame analysis - real PyAV frame extraction against a real,
# ffmpeg-generated video; captioning goes through the (mock, by
# default) Vision provider.
# ---------------------------------------------------------------------

_FFMPEG_MISSING = shutil.which("ffmpeg") is None


def _make_test_video(path: Path, duration: int = 6) -> None:
    subprocess.run(
        [
            "ffmpeg", "-y", "-f", "lavfi", "-i", f"sine=frequency=440:duration={duration}",
            "-f", "lavfi", "-i", f"testsrc=duration={duration}:size=160x120:rate=5",
            "-c:v", "libx264", "-c:a", "aac", "-shortest", str(path),
        ],
        check=True, capture_output=True,
    )


@pytest.mark.skipif(_FFMPEG_MISSING, reason="ffmpeg not installed in this environment")
def test_sample_frame_pngs_extracts_evenly_spaced_real_frames(tmp_path):
    video_path = tmp_path / "clip.mp4"
    _make_test_video(video_path, duration=6)

    frames = _sample_frame_pngs(video_path, 3)

    assert len(frames) == 3
    timestamps = [t for t, _ in frames]
    assert timestamps == sorted(timestamps)
    assert all(0 < t < 6 for t in timestamps)

    for _, png_bytes in frames:
        with Image.open(io.BytesIO(png_bytes)) as image:
            assert image.format == "PNG"
            assert image.size == (160, 120)


def test_sample_frame_pngs_returns_nothing_for_a_zero_count(tmp_path):
    assert _sample_frame_pngs(tmp_path / "irrelevant.mp4", 0) == []


def test_sample_frame_pngs_fails_softly_on_unopenable_bytes(tmp_path):
    bogus_path = tmp_path / "not_really_a_video.mp4"
    bogus_path.write_bytes(b"this is not a video container")

    assert _sample_frame_pngs(bogus_path, 3) == []


@pytest.mark.skipif(_FFMPEG_MISSING, reason="ffmpeg not installed in this environment")
def test_process_video_captions_real_frames_with_the_mock_vision_provider(tmp_path, monkeypatch):
    monkeypatch.setattr(
        "app.multimodal.video_processor.get_settings", lambda: SimpleNamespace(video_frame_sample_count=3)
    )
    video_path = tmp_path / "clip.mp4"
    _make_test_video(video_path, duration=6)

    results = process_video("clip.mp4", video_path.read_bytes())

    assert results[0].content_type == "transcript"
    frame_captions = [r for r in results if r.content_type == "frame_caption"]
    assert len(frame_captions) == 3
    for caption in frame_captions:
        assert caption.is_mock is True
        assert caption.provider == "mock"
        assert caption.text.startswith("[")  # "[<timestamp>s] <caption>"


@pytest.mark.skipif(_FFMPEG_MISSING, reason="ffmpeg not installed in this environment")
def test_process_video_skips_frame_captioning_when_sample_count_is_zero(tmp_path, monkeypatch):
    monkeypatch.setattr(
        "app.multimodal.video_processor.get_settings", lambda: SimpleNamespace(video_frame_sample_count=0)
    )
    video_path = tmp_path / "clip.mp4"
    _make_test_video(video_path, duration=2)

    results = process_video("clip.mp4", video_path.read_bytes())

    assert len(results) == 1
    assert results[0].content_type == "transcript"


@pytest.mark.skipif(_FFMPEG_MISSING, reason="ffmpeg not installed in this environment")
def test_process_video_keeps_the_transcript_even_if_every_frame_caption_fails(tmp_path, monkeypatch):
    monkeypatch.setattr(
        "app.multimodal.video_processor.get_settings", lambda: SimpleNamespace(video_frame_sample_count=2)
    )

    class _BrokenVisionProvider:
        name = "broken"

        def describe(self, image_bytes, filename):
            raise RuntimeError("vision API unavailable")

    monkeypatch.setattr("app.multimodal.video_processor.get_vision_provider", lambda: _BrokenVisionProvider())

    video_path = tmp_path / "clip.mp4"
    _make_test_video(video_path, duration=4)

    results = process_video("clip.mp4", video_path.read_bytes())

    assert len(results) == 1
    assert results[0].content_type == "transcript"
